name: deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.409
    - name: Restore dependencies
      run: |
        dotnet restore
        dotnet publish -c Release
        pwd
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.3.0
    - name: stelz
      run: |
        pwd
        cd /home/runner/work/LinkShorter/LinkShorter/LinkShorter/frontend
        export NODE_ENV=dev
        yarn install 
        yarn build
        ls -la /home/runner/work/LinkShorter/LinkShorter/LinkShorter/bin/Release/netcoreapp3.1/publish/
        
    


