name: .pipe

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release
    - uses: actions/setup-node@v2.1.4 
    - name: build vue
      run: |
        export NODE_ENV=dev
        cd LinkShorter/frontend
        npm install
        npm run build
        ls -la bin
        # mv dist bin/Release/netcoreapp3.1/publish/clientapp/dist
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build
      uses: docker/build-push-action@v2
      with:
          push: false
          load: true
          context: .
          file: ./Dockerfile
          tags: test/test:latest
   
