name: .pipe

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release
    - uses: actions/setup-node@v2.1.4 
    - name: build vue
      run: |
        export NODE_ENV=dev
        cd LinkShorter/frontend
        npm install
        npm run build
        rm -r ../bin/Release/netcoreapp3.1/publish/frontend
        mkdir ../bin/Release/netcoreapp3.1/publish/frontend-serve
        mv dist ../bin/Release/netcoreapp3.1/publish/frontend-serve
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.token }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build
      uses: docker/build-push-action@v2
      with:
          push: true
          load: false
          context: .
          file: ./Dockerfile
          tags: florian262000/linkshorter:latest
   
